### ISSUE TITLE
Data directory is created in current working directory

### ISSUE THREAD

**Issue by smijolovic** [ElCap1tan/gort#1]
Gort looks like a great project!

One issue is that the code appears to only look for data directory in the current working directory, and does not follow the path of the binary.

gort binary is in /usr/bin
data directory is in /usr/bin

$ gort 192.168.1.100
Known ports list under data/port-numbers.xml not found. Trying to download it from https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml...
Most common open ports list under data/port_open_freq.csv not found. Trying to download it from https://docs.google.com/spreadsheets/d/1r_IriqmkTNPSTiUwii_hQ8Gwl2tfTUz8AGIOIL-wMIE/export?format=csv...

It then creates the data directory and downloads the two files where the command was executed, vs following the path of gort.

**Comment by leyyce** [comment]
Hey thanks for your feedback. 

I have some still outstanding changes in my local git repo that I didn't come around to push anyways (had much to do because of my cs degree) so I might take a look at this problem in the next few days and get all the small changes and fixes that still are missing out.

This is one of my first major projects and my first project in Go at all, so feel free to provide additional feedback if you want to. Still learning :)
